# Generated by Django 5.0.6 on 2025-09-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisa', models.CharField(choices=[('COP', 'Peso Colombiano'), ('USD', 'Dólar Estadounidense')], max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField()),
                ('nombre_quien_realiza', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula'), ('PP', 'Pasaporte')], max_length=2)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('fecha_vencimiento', models.CharField(max_length=5)),
                ('codigo_seguridad', models.CharField(max_length=4)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Transacciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
